/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.91.0
  Forc version: 0.61.1
  Fuel-Core version: 0.30.0
*/

export type { USTanThetaDollarAbi } from './USTanThetaDollarAbi';

export { USTanThetaDollarAbi__factory } from './factories/USTanThetaDollarAbi__factory';
