/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.90.0
  Forc version: 0.60.0
  Fuel-Core version: 0.30.0
*/

import type {
  BytesLike,
  Contract,
  DecodedValue,
  FunctionFragment,
  Interface,
  InvokeFunction,
} from 'fuels';

interface YesnoTokensAbiInterface extends Interface {
  functions: {
    test_function: FunctionFragment;
  };
}

export class YesnoTokensAbi extends Contract {
  interface: YesnoTokensAbiInterface;
  functions: {
    test_function: InvokeFunction<[], boolean>;
  };
}
